"""Insert text into the focused app: clipboard + ⌘V, then restore the old clipboard.

The dictated text is marked transient/concealed (nspasteboard.org conventions) so
clipboard managers and Universal Clipboard skip it. Posting ⌘V needs Accessibility.
"""

from AppKit import NSData, NSPasteboard, NSPasteboardItem, NSPasteboardTypeString
from PyObjCTools import AppHelper
import Quartz

RESTORE_AFTER = 0.5  # seconds; long enough for slow (e.g. Electron) apps to read the paste
KEY_V = 9  # ANSI V. TODO: map via the current keyboard layout for Dvorak/AZERTY users.

_PRIVATE_TYPES = (
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
)


def _snapshot(pb):
    items = []
    for item in pb.pasteboardItems() or []:
        items.append({t: item.dataForType_(t) for t in item.types()})
    return items


def _restore(pb, saved):
    pb.clearContents()
    items = []
    for types in saved:
        item = NSPasteboardItem.alloc().init()
        for t, data in types.items():
            if data is not None:
                item.setData_forType_(data, t)
        items.append(item)
    if items:
        pb.writeObjects_(items)


def _post_cmd_v():
    source = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStateHIDSystemState)
    for down in (True, False):
        event = Quartz.CGEventCreateKeyboardEvent(source, KEY_V, down)
        # Exactly ⌘: don't inherit fn or other modifiers that may still be held.
        Quartz.CGEventSetFlags(event, Quartz.kCGEventFlagMaskCommand)
        Quartz.CGEventPost(Quartz.kCGSessionEventTap, event)


def copy_text(text):
    """Leave `text` on the clipboard for the user to paste themselves (no ⌘V, no restore)."""
    pb = NSPasteboard.generalPasteboard()
    pb.clearContents()
    pb.setString_forType_(text, NSPasteboardTypeString)
    pb.setData_forType_(NSData.data(), "org.nspasteboard.ConcealedType")  # keep it out of clipboard history


def paste_text(text):
    pb = NSPasteboard.generalPasteboard()
    saved = _snapshot(pb)
    pb.clearContents()
    pb.setString_forType_(text, NSPasteboardTypeString)
    for t in _PRIVATE_TYPES:
        pb.setData_forType_(NSData.data(), t)
    ours = pb.changeCount()
    _post_cmd_v()

    def restore():
        # If the user copied something in the meantime, leave their new clipboard alone.
        if pb.changeCount() == ours:
            _restore(pb, saved)

    AppHelper.callLater(RESTORE_AFTER, restore)
