"""Insert text into the focused app: clipboard + ⌘V, then restore the old clipboard.

The dictated text is marked transient/concealed (nspasteboard.org conventions) so
clipboard managers and Universal Clipboard skip it. Posting ⌘V needs Accessibility.
"""

from AppKit import NSData, NSPasteboard, NSPasteboardItem, NSPasteboardTypeString
from PyObjCTools import AppHelper
import Quartz

RESTORE_AFTER = 0.5  # seconds; long enough for slow (e.g. Electron) apps to read the paste
KEY_V = 9  # ANSI V. TODO: map via the current keyboard layout for Dvorak/AZERTY users.

_PRIVATE_TYPES = (
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
)


def _snapshot(pb):
    items = []
    for item in pb.pasteboardItems() or []:
        items.append({t: item.dataForType_(t) for t in item.types()})
    return items


def _restore(pb, saved):
    pb.clearContents()
    items = []
    for types in saved:
        item = NSPasteboardItem.alloc().init()
        for t, data in types.items():
            if data is not None:
                item.setData_forType_(data, t)
        items.append(item)
    if items:
        pb.writeObjects_(items)


def _post_cmd_v():
    source = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStateHIDSystemState)
    for down in (True, False):
        event = Quartz.CGEventCreateKeyboardEvent(source, KEY_V, down)
        # Exactly ⌘: don't inherit fn or other modifiers that may still be held.
        Quartz.CGEventSetFlags(event, Quartz.kCGEventFlagMaskCommand)
        Quartz.CGEventPost(Quartz.kCGSessionEventTap, event)


TYPE_CHUNK = 20  # characters per synthetic key event (macOS truncates longer strings)


def type_text(text, post=None):
    """Insert text as typed characters, never touching the clipboard (used in Incognito).
    Each key event carries up to TYPE_CHUNK characters as its Unicode string."""
    post = post or (lambda event: Quartz.CGEventPost(Quartz.kCGSessionEventTap, event))
    source = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStateHIDSystemState)
    for i in range(0, len(text), TYPE_CHUNK):
        chunk = text[i:i + TYPE_CHUNK]
        for down in (True, False):
            event = Quartz.CGEventCreateKeyboardEvent(source, 0, down)
            Quartz.CGEventSetFlags(event, 0)  # no fn/⌘ leaking in from held keys
            Quartz.CGEventKeyboardSetUnicodeString(event, len(chunk.encode("utf-16-le")) // 2, chunk)
            post(event)


KEY_RETURN = 36
ENTER_DELAY = 0.25  # seconds after the text goes in, so the app has taken the paste first


def press_enter(post=None):
    """Press Return once, with no modifiers (Auto-Enter: sends the message you just dictated)."""
    post = post or (lambda event: Quartz.CGEventPost(Quartz.kCGSessionEventTap, event))
    source = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStateHIDSystemState)
    for down in (True, False):
        event = Quartz.CGEventCreateKeyboardEvent(source, KEY_RETURN, down)
        Quartz.CGEventSetFlags(event, 0)  # a held ⇧ or ⌘ would make it a new line or something else
        post(event)


def copy_text(text):
    """Leave `text` on the clipboard for the user to paste themselves (no ⌘V, no restore)."""
    pb = NSPasteboard.generalPasteboard()
    pb.clearContents()
    pb.setString_forType_(text, NSPasteboardTypeString)
    pb.setData_forType_(NSData.data(), "org.nspasteboard.ConcealedType")  # keep it out of clipboard history


def paste_text(text):
    pb = NSPasteboard.generalPasteboard()
    saved = _snapshot(pb)
    pb.clearContents()
    pb.setString_forType_(text, NSPasteboardTypeString)
    for t in _PRIVATE_TYPES:
        pb.setData_forType_(NSData.data(), t)
    ours = pb.changeCount()
    _post_cmd_v()

    def restore():
        # If the user copied something in the meantime, leave their new clipboard alone.
        if pb.changeCount() == ours:
            _restore(pb, saved)

    AppHelper.callLater(RESTORE_AFTER, restore)
